##########################################
#        General Configuration           #
##########################################

#General Configuration
WEBHOOK-URL: "URL-HERE"

##########################################
#            Join Configuration          #
##########################################

JOIN: #{player}
  WEBHOOK-TITLE: "{player} Joined"
  WEBHOOK-COLOR: "#FFFFFF"
  WEBHOOK-THUMBNAIL: "https://cdn.discordapp.com/attachments/995528294613135440/1006600350087786676/unknown.png"
  WEBHOOK-DESCRIPTION:
    - ""
    - "{player}"
    - ""
  WEBHOOK-PERMISSION: "sparkdiscord.join"

##########################################
#            Quit Configuration          #
##########################################

QUIT: #{player}
  WEBHOOK-TITLE: "{player} Quit"
  WEBHOOK-COLOR: "#FFFFFF"
  WEBHOOK-THUMBNAIL: "https://cdn.discordapp.com/attachments/995528294613135440/1006600350087786676/unknown.png"
  WEBHOOK-DESCRIPTION:
    - ""
    - "{player}"
    - ""
  WEBHOOK-PERMISSION: "sparkdiscord.quit"

##########################################
#           Death Configuration          #
##########################################

DEATH: #{player} {cause}
  WEBHOOK-TITLE: "{player} Died"
  WEBHOOK-COLOR: "#FFFFFF"
  WEBHOOK-THUMBNAIL: "https://cdn.discordapp.com/attachments/995528294613135440/1006600350087786676/unknown.png"
  WEBHOOK-DESCRIPTION:
    - ""
    - "{player} {cause}"
    - ""
  WEBHOOK-PERMISSION: "sparkdiscord.death"
##########################################
#            Chat Configuration          #
##########################################

CHAT: #{player} {message}
  WEBHOOK-TITLE: "{player} Said"
  WEBHOOK-COLOR: "#FFFFFF"
  WEBHOOK-THUMBNAIL: "https://cdn.discordapp.com/attachments/995528294613135440/1006600350087786676/unknown.png"
  WEBHOOK-DESCRIPTION:
    - ""
    - "{message}"
    - ""
  WEBHOOK-PERMISSION: "sparkdiscord.chat"

##########################################
#            CMD Configuration           #
##########################################

CMD: #{player} {command}
  WEBHOOK-TITLE: "{player} Executed"
  WEBHOOK-COLOR: "#FFFFFF"
  WEBHOOK-THUMBNAIL: "https://cdn.discordapp.com/attachments/995528294613135440/1006600350087786676/unknown.png"
  WEBHOOK-DESCRIPTION:
    - ""
    - "{command}"
    - ""
  WEBHOOK-PERMISSION: "sparkdiscord.cmd"

##########################################
#          Server Configuration          #
##########################################

START:
  WEBHOOK-TITLE: "Server Started"
  WEBHOOK-COLOR: "#FFFFFF"
  WEBHOOK-THUMBNAIL: "https://cdn.discordapp.com/attachments/995528294613135440/1006600350087786676/unknown.png"
  WEBHOOK-DESCRIPTION:
    - ""
    - "A new server has been started!"
    - ""

STOP:
  WEBHOOK-TITLE: "Server Stopped"
  WEBHOOK-COLOR: "#FFFFFF"
  WEBHOOK-THUMBNAIL: "https://cdn.discordapp.com/attachments/995528294613135440/1006600350087786676/unknown.png"
  WEBHOOK-DESCRIPTION:
    - ""
    - "The server has been stopped!"
    - ""
